CONFIG_ZMK_SENSOR_TPS65=y
CONFIG_ZMK_SENSOR_TPS65_GESTURE_SUPPORT=y
CONFIG_ZMK_SENSOR_TPS65_POLL_RATE_MS=10
CONFIG_ZMK_SENSOR_TPS65_MAX_TOUCHES=5
CONFIG_ZMK_SENSOR_TPS65_SENSITIVITY=40
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_GPIO=y